### ISSUE TITLE
Compilation failed when there is no exported method

### ISSUE THREAD

**Issue by JeremyAnsel** [AaronRobinsonMSFT/DNNE#155] opened 2023-02-20 19:57 UTC
Hello,
I've created a new Class Library project named DnneTest.
Then I've added the DNNE nuget package.
When I compile the project, I get this error:
> Generated source file(s), obj\Debug\net6.0\dnne/DnneTest.g.c, not found. In order to generate source an export must exist. Create an export by adorning a function with UnmanagedCallersOnly.	DnneTest	C:\Users\jerem\.nuget\packages\dnne\2.0.0\build\DNNE.targets	121	

I was expecting the project to compile fine even when there is no exported method.

**Comment by AaronRobinsonMSFT** [comment] 2023-02-20 22:37
> I was expecting the project to compile fine even when there is no exported method.

Yep, this is by design. If the project isn't exporting a function then it shouldn't reference DNNE. Is there a scenario where this is desired?

**Comment by AaronRobinsonMSFT** [comment] 2023-02-20 23:40
Another option is to set the following property in your project: `<DnneBuildExports>false</DnneBuildExports>`

**Comment by AaronRobinsonMSFT** [comment] 2023-02-23 22:37
@JeremyAnsel I'm going to close this as "by-design". A goal of mine was to avoid people adding packages they are not using. If someone needs to reference this package _and_ not create an export I would ask them to set in `<DnneBuildExports>false</DnneBuildExports>` their project.

**Closed by AaronRobinsonMSFT** 2023-02-23 22:37 UTC
Labels: question

**Comment by JeremyAnsel** [comment] 2023-02-24 21:10
There is no scenario where I need it. It was just a question.
IIRC when you add the package the compilation fails. Once you export a method the compilation succeeds. If you remove the method the compilation still succeeds.
